services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user     
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=test
    command: ["redis-server", "--requirepass", "my_redis_password"]
